INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (1,'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.',882,123);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (2,'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.',961,213);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (3,'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.',560,148);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (4,'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.',587,206);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (5,'Sed vel enim sit amet nunc viverra dapibus.',734,278);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (6,'Curabitur gravida nisi at nibh.',684,262);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (7,'Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.',412,146);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (8,'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.',536,99);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (9,'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.',644,222);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (10,'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.',462,244);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (11,'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.',156,295);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (12,'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.',309,143);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (13,'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.',962,235);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (14,'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.',172,177);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (15,'Nulla tempus.',136,385);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (16,'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.',22,394);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (17,'Praesent blandit lacinia erat.',183,299);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (18,'Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.',586,338);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (19,'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.',128,99);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (20,'Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.',684,395);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (21,'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.',458,106);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (22,'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.',911,356);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (23,'Nulla justo.',405,52);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (24,'Cras pellentesque volutpat dui.',410,289);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (25,'Morbi ut odio.',663,343);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (26,'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.',313,396);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (27,'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.',23,135);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (28,'Nulla suscipit ligula in lacus.',483,232);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (29,'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.',745,181);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (30,'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.',613,151);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (31,'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.',593,25);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (32,'Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.',646,213);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (33,'Quisque ut erat. Curabitur gravida nisi at nibh.',681,32);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (34,'Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.',601,349);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (35,'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.',158,311);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (36,'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.',21,357);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (37,'Aliquam quis turpis eget elit sodales scelerisque.',740,322);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (38,'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.',490,76);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (39,'In hac habitasse platea dictumst.',935,80);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (40,'Nunc rhoncus dui vel sem.',90,376);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (41,'Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.',175,172);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (42,'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.',713,328);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (43,'Curabitur gravida nisi at nibh.',18,374);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (44,'Donec ut mauris eget massa tempor convallis.',995,117);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (45,'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.',98,5);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (46,'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.',794,217);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (47,'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.',389,370);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (48,'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.',329,345);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (49,'Maecenas rhoncus aliquam lacus.',967,231);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (50,'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.',234,339);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (51,'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.',507,378);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (52,'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl.',652,268);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (53,'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.',767,247);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (54,'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat.',905,335);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (55,'Nulla tellus.',85,167);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (56,'Praesent blandit lacinia erat.',572,76);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (57,'Nulla tellus. In sagittis dui vel nisl.',828,264);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (58,'Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo.',910,200);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (59,'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.',961,366);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (60,'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.',225,252);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (61,'In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.',489,389);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (62,'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.',464,297);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (63,'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.',495,138);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (64,'Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.',616,293);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (65,'Pellentesque viverra pede ac diam.',840,8);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (66,'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.',566,255);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (67,'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.',282,344);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (68,'Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.',3,79);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (69,'In est risus, auctor sed, tristique in, tempus sit amet, sem.',617,247);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (70,'Donec quis orci eget orci vehicula condimentum.',726,359);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (71,'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.',417,106);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (72,'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.',803,308);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (73,'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.',490,323);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (74,'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.',595,159);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (75,'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.',731,85);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (76,'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.',434,91);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (77,'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.',383,317);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (78,'Etiam vel augue.',646,252);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (79,'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.',675,152);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (80,'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.',225,146);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (81,'Phasellus id sapien in sapien iaculis congue.',94,331);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (82,'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.',49,221);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (83,'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.',853,216);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (84,'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',360,223);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (85,'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.',135,240);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (86,'Proin risus. Praesent lectus.',664,363);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (87,'Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo.',564,16);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (88,'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.',669,385);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (89,'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.',696,193);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (90,'Morbi non lectus.',531,384);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (91,'Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.',611,49);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (92,'Sed ante.',458,69);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (93,'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.',283,231);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (94,'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.',181,157);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (95,'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',964,134);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (96,'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.',849,91);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (97,'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.',27,335);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (98,'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.',54,301);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (99,'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.',667,79);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (100,'Phasellus in felis. Donec semper sapien a libero.',742,312);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (101,'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.',213,351);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (102,'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.',455,196);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (103,'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',827,287);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (104,'Ut at dolor quis odio consequat varius.',645,139);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (105,'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.',393,185);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (106,'Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.',398,8);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (107,'Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.',932,71);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (108,'Morbi ut odio.',71,110);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (109,'Curabitur at ipsum ac tellus semper interdum.',444,257);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (110,'Praesent blandit. Nam nulla.',84,258);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (111,'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.',288,362);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (112,'Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus.',767,270);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (113,'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.',673,47);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (114,'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.',881,21);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (115,'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.',807,134);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (116,'Curabitur gravida nisi at nibh.',516,133);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (117,'Morbi a ipsum. Integer a nibh.',467,220);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (118,'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.',367,317);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (119,'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.',339,266);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (120,'Nulla facilisi. Cras non velit nec nisi vulputate nonummy.',837,338);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (121,'Nunc purus. Phasellus in felis.',119,225);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (122,'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',299,390);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (123,'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.',172,217);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (124,'Morbi vel lectus in quam fringilla rhoncus.',661,189);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (125,'Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.',170,150);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (126,'Etiam faucibus cursus urna.',833,49);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (127,'Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.',201,95);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (128,'Donec vitae nisi.',491,213);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (129,'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.',811,174);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (130,'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.',385,325);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (131,'Pellentesque at nulla. Suspendisse potenti.',304,291);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (132,'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.',624,74);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (133,'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.',347,142);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (134,'Integer a nibh. In quis justo.',515,197);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (135,'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.',741,364);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (136,'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.',894,284);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (137,'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.',1,188);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (138,'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.',60,389);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (139,'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.',299,388);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (140,'Duis at velit eu est congue elementum. In hac habitasse platea dictumst.',593,168);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (141,'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.',814,248);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (142,'Nunc purus. Phasellus in felis. Donec semper sapien a libero.',9,324);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (143,'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.',623,100);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (144,'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.',850,342);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (145,'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.',53,365);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (146,'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.',89,96);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (147,'Pellentesque viverra pede ac diam.',172,42);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (148,'Phasellus sit amet erat.',1,135);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (149,'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.',95,384);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (150,'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.',700,39);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (151,'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.',51,69);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (152,'Praesent blandit lacinia erat.',908,397);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (153,'Maecenas pulvinar lobortis est.',360,56);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (154,'Quisque ut erat. Curabitur gravida nisi at nibh.',680,396);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (155,'Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.',627,70);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (156,'Duis consequat dui nec nisi volutpat eleifend.',975,2);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (157,'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.',813,209);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (158,'Aliquam sit amet diam in magna bibendum imperdiet.',994,124);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (159,'Aliquam non mauris. Morbi non lectus.',160,85);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (160,'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio.',215,329);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (161,'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.',141,340);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (162,'Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.',1000,269);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (163,'Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo.',194,31);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (164,'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl.',329,87);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (165,'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.',31,32);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (166,'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.',852,200);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (167,'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.',188,271);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (168,'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.',389,62);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (169,'Aenean lectus. Pellentesque eget nunc.',381,260);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (170,'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.',502,27);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (171,'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.',966,131);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (172,'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.',938,158);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (173,'Nulla mollis molestie lorem.',653,107);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (174,'Donec posuere metus vitae ipsum.',624,272);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (175,'Phasellus id sapien in sapien iaculis congue.',930,59);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (176,'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.',840,196);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (177,'Sed sagittis.',884,178);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (178,'Curabitur at ipsum ac tellus semper interdum.',780,106);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (179,'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.',84,348);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (180,'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.',749,147);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (181,'Phasellus in felis.',796,152);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (182,'Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.',881,204);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (183,'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.',803,219);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (184,'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.',24,332);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (185,'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.',715,140);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (186,'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.',903,151);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (187,'Nullam varius. Nulla facilisi.',623,246);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (188,'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.',107,191);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (189,'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.',900,54);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (190,'Vivamus vel nulla eget eros elementum pellentesque.',409,400);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (191,'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.',421,269);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (192,'Suspendisse potenti.',706,284);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (193,'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.',329,396);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (194,'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.',875,76);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (195,'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.',675,273);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (196,'Phasellus id sapien in sapien iaculis congue.',618,340);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (197,'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.',764,38);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (198,'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.',959,29);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (199,'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.',639,168);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (200,'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.',113,21);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (201,'Phasellus sit amet erat.',22,392);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (202,'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.',627,171);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (203,'Praesent lectus.',532,1);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (204,'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.',517,221);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (205,'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.',687,370);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (206,'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.',504,223);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (207,'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.',118,240);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (208,'Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.',432,385);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (209,'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.',809,387);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (210,'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.',936,264);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (211,'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.',583,307);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (212,'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.',46,239);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (213,'Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.',708,7);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (214,'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.',851,356);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (215,'Vestibulum ac est lacinia nisi venenatis tristique.',686,65);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (216,'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.',634,86);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (217,'Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.',400,376);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (218,'Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.',130,371);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (219,'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.',719,144);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (220,'Phasellus sit amet erat.',201,57);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (221,'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.',454,124);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (222,'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.',690,265);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (223,'Nulla ac enim.',286,203);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (224,'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.',104,274);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (225,'Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.',905,306);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (226,'Proin risus.',895,169);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (227,'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.',409,84);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (228,'Pellentesque ultrices mattis odio.',1000,194);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (229,'Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.',660,81);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (230,'Nulla tempus.',117,235);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (231,'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.',286,270);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (232,'Sed vel enim sit amet nunc viverra dapibus.',337,99);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (233,'Donec posuere metus vitae ipsum.',414,250);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (234,'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.',431,23);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (235,'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.',859,132);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (236,'Nulla facilisi.',544,236);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (237,'Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.',515,318);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (238,'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.',626,192);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (239,'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.',171,93);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (240,'Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.',18,135);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (241,'Vivamus tortor.',449,129);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (242,'Duis mattis egestas metus. Aenean fermentum.',273,190);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (243,'Integer ac neque.',711,177);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (244,'Maecenas ut massa quis augue luctus tincidunt.',503,130);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (245,'Vivamus tortor.',419,102);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (246,'Nullam varius. Nulla facilisi.',130,341);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (247,'Integer a nibh.',926,257);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (248,'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.',867,164);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (249,'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.',196,256);
INSERT INTO Comments(comment_id,content,parent_book,comment_author) VALUES (250,'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.',822,202);

UPDATE Comments SET replying_to = 1 WHERE comment_id= 3;
UPDATE Comments SET replying_to = 1 WHERE comment_id= 8;
UPDATE Comments SET replying_to = 6 WHERE comment_id= 9;
UPDATE Comments SET replying_to = 3 WHERE comment_id= 11;
UPDATE Comments SET replying_to = 10 WHERE comment_id= 18;
UPDATE Comments SET replying_to = 2 WHERE comment_id= 19;
UPDATE Comments SET replying_to = 2 WHERE comment_id= 21;
UPDATE Comments SET replying_to = 10 WHERE comment_id= 26;
UPDATE Comments SET replying_to = 26 WHERE comment_id= 29;
UPDATE Comments SET replying_to = 14 WHERE comment_id= 31;
UPDATE Comments SET replying_to = 9 WHERE comment_id= 32;
UPDATE Comments SET replying_to = 3 WHERE comment_id= 33;
UPDATE Comments SET replying_to = 31 WHERE comment_id= 34;
UPDATE Comments SET replying_to = 35 WHERE comment_id= 38;
UPDATE Comments SET replying_to = 26 WHERE comment_id= 45;
UPDATE Comments SET replying_to = 33 WHERE comment_id= 47;
UPDATE Comments SET replying_to = 35 WHERE comment_id= 52;
UPDATE Comments SET replying_to = 39 WHERE comment_id= 53;
UPDATE Comments SET replying_to = 2 WHERE comment_id= 58;
UPDATE Comments SET replying_to = 31 WHERE comment_id= 59;
UPDATE Comments SET replying_to = 4 WHERE comment_id= 62;
UPDATE Comments SET replying_to = 10 WHERE comment_id= 66;
UPDATE Comments SET replying_to = 63 WHERE comment_id= 67;
UPDATE Comments SET replying_to = 26 WHERE comment_id= 75;
UPDATE Comments SET replying_to = 19 WHERE comment_id= 76;
UPDATE Comments SET replying_to = 34 WHERE comment_id= 79;
UPDATE Comments SET replying_to = 46 WHERE comment_id= 82;
UPDATE Comments SET replying_to = 61 WHERE comment_id= 92;
UPDATE Comments SET replying_to = 50 WHERE comment_id= 94;
UPDATE Comments SET replying_to = 34 WHERE comment_id= 95;
UPDATE Comments SET replying_to = 36 WHERE comment_id= 96;
UPDATE Comments SET replying_to = 61 WHERE comment_id= 97;
UPDATE Comments SET replying_to = 71 WHERE comment_id= 98;
UPDATE Comments SET replying_to = 48 WHERE comment_id= 104;
UPDATE Comments SET replying_to = 45 WHERE comment_id= 110;
UPDATE Comments SET replying_to = 98 WHERE comment_id= 112;
UPDATE Comments SET replying_to = 52 WHERE comment_id= 113;
UPDATE Comments SET replying_to = 69 WHERE comment_id= 116;
UPDATE Comments SET replying_to = 1 WHERE comment_id= 126;
UPDATE Comments SET replying_to = 67 WHERE comment_id= 134;
UPDATE Comments SET replying_to = 71 WHERE comment_id= 137;
UPDATE Comments SET replying_to = 108 WHERE comment_id= 140;
UPDATE Comments SET replying_to = 127 WHERE comment_id= 146;
UPDATE Comments SET replying_to = 56 WHERE comment_id= 147;
UPDATE Comments SET replying_to = 137 WHERE comment_id= 152;
UPDATE Comments SET replying_to = 8 WHERE comment_id= 153;
UPDATE Comments SET replying_to = 13 WHERE comment_id= 156;
UPDATE Comments SET replying_to = 112 WHERE comment_id= 157;
UPDATE Comments SET replying_to = 61 WHERE comment_id= 158;
UPDATE Comments SET replying_to = 100 WHERE comment_id= 160;
UPDATE Comments SET replying_to = 110 WHERE comment_id= 161;
UPDATE Comments SET replying_to = 39 WHERE comment_id= 162;
UPDATE Comments SET replying_to = 66 WHERE comment_id= 168;
UPDATE Comments SET replying_to = 17 WHERE comment_id= 173;
UPDATE Comments SET replying_to = 8 WHERE comment_id= 175;
UPDATE Comments SET replying_to = 102 WHERE comment_id= 176;
UPDATE Comments SET replying_to = 96 WHERE comment_id= 181;
UPDATE Comments SET replying_to = 89 WHERE comment_id= 182;
UPDATE Comments SET replying_to = 134 WHERE comment_id= 185;
UPDATE Comments SET replying_to = 5 WHERE comment_id= 186;
UPDATE Comments SET replying_to = 152 WHERE comment_id= 189;
UPDATE Comments SET replying_to = 154 WHERE comment_id= 193;
UPDATE Comments SET replying_to = 10 WHERE comment_id= 195;
UPDATE Comments SET replying_to = 22 WHERE comment_id= 198;
UPDATE Comments SET replying_to = 42 WHERE comment_id= 200;
UPDATE Comments SET replying_to = 79 WHERE comment_id= 202;
UPDATE Comments SET replying_to = 186 WHERE comment_id= 204;
UPDATE Comments SET replying_to = 61 WHERE comment_id= 207;
UPDATE Comments SET replying_to = 72 WHERE comment_id= 214;
UPDATE Comments SET replying_to = 87 WHERE comment_id= 217;
UPDATE Comments SET replying_to = 191 WHERE comment_id= 218;
UPDATE Comments SET replying_to = 120 WHERE comment_id= 228;
UPDATE Comments SET replying_to = 214 WHERE comment_id= 237;
UPDATE Comments SET replying_to = 134 WHERE comment_id= 239;
UPDATE Comments SET replying_to = 233 WHERE comment_id= 244;
UPDATE Comments SET replying_to = 172 WHERE comment_id= 250;
